name: OpenMM-Build-Wheels

env:
  GIT_REVISION: 'master'

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  unix:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}
    strategy:
      matrix:
        python-version: ["3.10"]
        include:
          - name: MacOS ARM
            os: macos-latest
            requirements: macos

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        name: "Install Python"
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Install dependencies"
        run: pip install -r devtools/requirements/${{ matrix.requirements }}.txt

      - name: "Install Homebrew"
        if: startsWith(matrix.os, 'macos')
        uses: Homebrew/actions/setup-homebrew@master

      - name: "Install Doxygen"
        if: startsWith(matrix.os, 'macos')
        run: brew install doxygen

      - name: "Set SDK on MacOS (if needed)"
        if: startsWith(matrix.os, 'macos')
        run: source devtools/scripts/install_macos_sdk.sh

      - name: "Check out OpenMM source code"
        run: |
          git clone https://github.com/openmm/openmm.git
          cd openmm
          git checkout $GIT_REVISION
          git apply ${{ github.workspace }}/devtools/patches/library_path.patch

      - name: "Configure build with CMake"
        shell: bash -l {0}
        run: |
          cd openmm
          mkdir build
          cd build

          cmake .. \
            -DCMAKE_INSTALL_PREFIX=${HOME}/openmm-install \
            ${{ matrix.CMAKE_FLAGS }}

      - name: "Build OpenMM"
        shell: bash -l {0}
        run: |
          cd openmm/build
          make -j4 install

      - name: "Build Python wrappers"
        shell: bash -l {0}
        run: |
          cd openmm/build
          make -j4 PythonInstall

      - name: "Test Python wrappers"
        shell: bash -l {0}
        run: |
          set -x
          ls -R /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/openmm/../OpenMM.libs/lib
          python -m openmm.testInstallation
          python -c "import openmm as mm; print(mm.version.openmm_library_path)"
          python -c "import openmm as mm; print('---Loaded---', *mm.pluginLoadedLibNames, '---Failed---', *mm.Platform.getPluginLoadFailures(), sep='\n')"

      - name: "Build wheel"
        shell: bash -l {0}
        run: |
          cd openmm/build/python
          pip wheel . --wheel-dir=dist
          export DYLD_LIBRARY_PATH=${HOME}/openmm-install/lib
          cd dist
          python -m delocate.cmd.delocate_wheel -w fixed -v *.whl -L "../OpenMM.libs/lib"
          python ${{ github.workspace }}/devtools/scripts/add_plugins_and_headers.py "${HOME}/openmm-install"